// O11.1: the Progression ranks the user approved (docs/RANGI.txt), one per level 1-1 .. 7-5 and a single maximum
// one from 8-1 on. ranks.cpp is generated by tools/gen_ranks.py; edit the list, not the generated file.
#pragma once

#include <string>

namespace cr {

// "1-2" for level 2: five levels to a world (ui/lang.cpp)
std::string levelLabel(int level);

// levels with a rank of their own (7 worlds x 5)
int rankCount();

// the rank of `level` (1-based) in the current language (ui/lang.h); levels past rankCount() share the maximum one
const char *rankName(int level);

} // namespace cr
