// generated by tools/gen_ranks.py from docs/RANGI.txt - do not edit
#include "ui/ranks.h"

#include "ui/lang.h"

namespace cr {

// { English, Polish } for levels 1-1 up (index = level - 1)
static const char *const kRanks[35][2] = {
    {"Speed Bump", "Prog Zwalniajacy"},
    {"Road Snack", "Przekaska dla Tira"},
    {"Professional Tree Hugger", "Zawodowy Przytulacz Drzew"},
    {"Accidental Pedestrian", "Przypadkowy Przechodzien"},
    {"Almost Roadkill", "Prawie Rozjechany"},
    {"Puddle Jumper", "Skoczek przez Kaluze"},
    {"Log Surfer Trainee", "Stazysta na Klodzie"},
    {"Crosswalk Rookie", "Swiezak na Pasach"},
    {"Bumper Dodger", "Unikacz Zderzakow"},
    {"Critter with a Plan", "Zwierzak z Planem"},
    {"Traffic Whisperer", "Zaklinacz Ruchu"},
    {"Lily Pad Captain", "Kapitan Lilii"},
    {"Rail Dancer", "Tancerz na Torach"},
    {"Roadside Ninja", "Ninja z Pobocza"},
    {"Crossing Veteran", "Weteran Przejsc"},
    {"Asphalt Acrobat", "Akrobata Asfaltu"},
    {"River Tamer", "Pogromca Rzeki"},
    {"Train Teaser", "Ten, co Drazni Pociagi"},
    {"Sergeant Snout", "Sierzant Ryjek"},
    {"Boss of the Street", "Szef Ulicy"},
    {"Highway Hero", "Bohater Autostrady"},
    {"Captain Crossroads", "Kapitan Skrzyzowanie"},
    {"Lord of the Logs", "Wladca Klod"},
    {"Major Mayhem", "Major Zamieszanie"},
    {"Commander of Crossings", "Komendant Przejsc"},
    {"Iron Nerve", "Zelazne Nerwy"},
    {"Storm on Legs", "Burza na Nozkach"},
    {"General Gridlock", "General Korek"},
    {"Drivers' Nightmare", "Postrach Kierowcow"},
    {"Master of the Road", "Mistrz Drogi"},
    {"Legend of the Lane", "Legenda Pasa"},
    {"Myth of the Motorway", "Mit Autostrady"},
    {"Golden Step", "Zloty Krok"},
    {"Supreme Crosser", "Najwyzszy Przechodzien"},
    {"The One Who Crossed", "Ten, Ktory Przeszedl"},
};
static const char *const kTopRank[2] = {"Unkillable Legend", "Niesmiertelna Legenda"};

int rankCount() { return 35; }

const char *rankName(int level)
{
    const int i = level - 1;
    return i < 0 ? kRanks[0][lang::current()] : i < 35 ? kRanks[i][lang::current()]
                                                                 : kTopRank[lang::current()];
}

} // namespace cr
