// Screens drawn over the game (src/screens/*.tsx and the overlays of src/app/index.tsx). Animations advance per
// logic step (1/60 s), so a replay shows the same frames. Implemented: Home (4.2b) with the mode menu of O11.2,
// Game Over and the restart fade (4.2c), Pause (4.2d) and Settings (4.2e) — the last two are the port's own,
// styled like SettingsScreen.
#pragma once

#include <functional>
#include <string>

#include "engine/input.h"
#include "engine/renderer.h"
#include "engine/text.h"
#include "ui/lang.h"

namespace cr {

class Game;

// src/Characters.ts: the original ships only the chicken enabled; the other six are commented out there but their
// models are in the game (task 7.1 makes them selectable)
struct CharacterInfo {
    const char *id;
    const char *name;
};
// O14: the beaver is ours - generated by tools/make_beaver.py, not taken from anyone else's model - and since O15
// it is the game's own hero, with the chicken kept as one of the alternatives
// The Amiga's compiler (gcc 6.5) stops at C++14 and has no inline variables; a const array at namespace scope has
// internal linkage anyway, so there it is simply `static`. Every C++17 build sees the line it always had.
#if __cplusplus >= 201703L
inline
#else
static
#endif
const CharacterInfo kCharacters[] = {{"beaver", "BEAVER"},     {"chicken", "CHICKEN"},   {"bacon", "BACON"},
                                            {"brent", "BRENT VATNE"}, {"avocoder", "AVOCODER"}, {"wheeler", "WHEELER"},
                                            {"palmer", "PALMER"},     {"juwan", "JUWAN"}};
constexpr int kCharacterCount = 8;

// what the settings screen edits; saved in conf/crossy.cfg by the app
struct UserSettings {
    int volume = 10;   // 0..10, sound effects
    int music = 22;    // percent, 0..100 in steps of 2
    int shadows = 0;   // 0 full, 1 simple, 2 off
    bool fpsCounter = false;
    int framing = 0;   // 0 normal (view scale 3), 1 wide (3.5)
    int character = 0; // 7.1: index into kCharacters
    int language = 0;  // O11.5: 0 English, 1 Polish (ui/lang.h)
    // O23: how many play, and which input device each of them uses. The devices are the platform's own - the app
    // hands their names to Screens::controlNames - so this screen works the same on a keyboard and on a console.
    int players = 1;
    int control[2] = {0, 1};
};

struct MenuResult {
    bool resume = false, quitToHome = false, exitGame = false, settingsChanged = false;
    // O11.2: the home screen picked a game — 0 = Classic, k > 0 = Progression level k; -1 = nothing picked
    int startLevel = -1;
    // O11.4: New Game was confirmed, so the saved Progression progress goes back to level 1
    bool resetCareer = false;
};

enum class Menu { None, Pause, Settings };

// O23: the settings screen is a SCROLLING list now - the two control entries do not fit on one screenful, and the
// user asked for exactly this ("musimy chyba zrobic przewijane menu"). The order is the order they are shown in.
enum SettingsItem {
    SetPlayers, SetControl1, SetControl2, SetSounds, SetMusic, SetView, SetLanguage, SetCharacter, SetShadows,
    SetFps, SetBack, SetItemCount
};

class Screens {
public:
    bool load(Renderer &renderer, const std::string &dataDir);

    // once per logic step
    void update(const Game &game);
    void draw(Renderer &renderer, TextRenderer &text, const Game &game, int screenW, int screenH);
    // transitionToGamePlayingState: the GL view fades out (200 ms) and back in (300 ms) on restart; draw right
    // after the 3D scene, before the HUD (the score is outside the faded view in the original)
    void drawSceneFade(Renderer &renderer, int screenW, int screenH);

    void openPause();
    void openSettings(bool fromPause);
    Menu menu() const { return menu_; }
    // the game must not step: the pause menu, or settings opened from it
    bool pausesGame() const { return menu_ == Menu::Pause || (menu_ == Menu::Settings && settingsFromPause_); }
    // an open menu or the home screen takes the step's input first; true = consumed, the game must not see it
    bool handleInput(const Input &input, UserSettings &settings, MenuResult &out);

    // UI sounds (banner, buttons) for the audio mixer
    std::function<void(const std::string &)> playSound;
    // current values shown by the settings screen
    const UserSettings *settings = nullptr;
    // O11.4: the Progression level the player may start (1 = nothing finished yet); the app keeps it in its config
    int careerLevel = 1;
    // shown small in the corner of the home screen when set (the SF2000 build: the user tests by version number)
    std::string versionLabel;
    // O23: the input devices this platform offers, in the order the settings screen steps through them (for example
    // ARROWS, WSAD, JOY 1, JOY 2). Left null on a platform with one device, and the control entries then vanish.
    const char *const *controlNames = nullptr;
    int controlCount = 0;

private:
    void drawHome(Renderer &renderer, TextRenderer &text, int screenW, int screenH);
    void drawGameOver(Renderer &renderer, TextRenderer &text, const Game &game, int screenW, int screenH);
    void drawPause(Renderer &renderer, TextRenderer &text, int screenW, int screenH);
    void drawSettings(Renderer &renderer, TextRenderer &text, int screenW, int screenH);
    // O11.2: the game over screen's banners, in the home screen's colours, as menu items
    void drawMenuBars(Renderer &renderer, TextRenderer &text, const std::string *labels, int count, int cursor, int w,
                      int top);
    bool handleHome(const Input &input, MenuResult &out);
    // O23: which entries the settings screen shows right now (the second control only with two players, and no
    // control entries at all when the platform offers one device); returns how many
    int settingsItems(const UserSettings &s, SettingsItem *out) const;
    // how many rows of the list fit between the title and the hint line
    static int visibleRows(int h);
    static lang::Str settingsLabel(SettingsItem item);
    std::string settingsValue(SettingsItem item, const UserSettings &s) const;

    // O11.2/O11.4: what the home screen shows — the two modes, the career menu behind Progression, and the
    // confirmation New Game needs before the saved progress goes
    enum class HomePage { Modes, Career, Confirm };

    Menu menu_ = Menu::None;
    bool settingsFromPause_ = false;
    int cursor_ = 0;
    int scrollTop_ = 0; // O23: first list row on screen
    HomePage homePage_ = HomePage::Modes;
    int homeCursor_ = 0, careerCursor_ = 0, confirmCursor_ = 0;
    GpuTexture title_, buttonPlay_, buttonSettings_, buttonBack_;
    int lastState_ = -1;
    real stateTime_ = 0;   // seconds since the game state last changed
    real pageTime_ = 0;    // seconds since the home screen's page last changed (the bars' entry)
    int homeVisits_ = 0;   // HomeScreen mounts
    int bestAtStart_ = 0;  // highscore when the current game started (NEW BEST)
    real fadeTime_ = -1;   // seconds into the restart fade, -1 = none
};

} // namespace cr
