#!/usr/bin/env python3
"""Turns a baked .fnt (CRF1, tools/bake_font.py) into a C header with a 1-bit atlas, so the SF2000 core can print its
start-up stages before any file is read from the SD card.

    python tools/font_to_header.py data/fonts/retro_12.fnt out/sf2000/gen/boot_font.h
"""
import os
import struct
import sys


def parse(buf, endian):
    if buf[:4] != b"CRF1":
        raise ValueError("not a CRF1 font")
    u16 = endian + "H"
    pos = 4
    atlas_w, atlas_h, pixel_size, line_height, count = struct.unpack_from(endian + "5H", buf, pos)
    pos += 10
    glyphs = {}
    for _ in range(count):
        cp, x, y, w, h, xoff, yoff, adv = struct.unpack_from(endian + "HHHHHhhH", buf, pos)
        pos += 16
        glyphs[cp] = (x, y, w, h, xoff, yoff, adv)
    if pos + atlas_w * atlas_h != len(buf):
        raise ValueError("size mismatch")
    return atlas_w, atlas_h, pixel_size, line_height, glyphs, buf[pos:pos + atlas_w * atlas_h]


def main():
    src, dst = sys.argv[1], sys.argv[2]
    buf = open(src, "rb").read()
    try:
        atlas_w, atlas_h, pixel_size, line_height, glyphs, coverage = parse(buf, "<")
    except (ValueError, struct.error):
        atlas_w, atlas_h, pixel_size, line_height, glyphs, coverage = parse(buf, ">")

    bits = bytearray((atlas_w * atlas_h + 7) // 8)
    for i, c in enumerate(coverage):
        if c >= 128:
            bits[i >> 3] |= 1 << (i & 7)

    out = []
    out.append("// generated by tools/font_to_header.py from %s - do not edit" % os.path.basename(src).replace("\\", "/"))
    out.append("#pragma once")
    out.append("")
    out.append("static const int kBootFontAtlasW = %d, kBootFontAtlasH = %d, kBootFontLineHeight = %d;"
               % (atlas_w, atlas_h, line_height))
    out.append("struct BootGlyph { unsigned short x, y, w, h; short xoff, yoff; unsigned short advance; };")
    out.append("static const BootGlyph kBootFontGlyphs[128] = {")
    for cp in range(128):
        g = glyphs.get(cp, (0, 0, 0, 0, 0, 0, 0))
        out.append("    {%d, %d, %d, %d, %d, %d, %d}," % g)
    out.append("};")
    out.append("// atlas coverage >= 128, bit i of byte i/8 = pixel i (rows top-first)")
    out.append("static const unsigned char kBootFontBits[%d] = {" % len(bits))
    for i in range(0, len(bits), 24):
        out.append("    " + ", ".join("%d" % b for b in bits[i:i + 24]) + ",")
    out.append("};")
    os.makedirs(os.path.dirname(dst) or ".", exist_ok=True)
    with open(dst, "w", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print("font_to_header: %s -> %s (%dx%d atlas, %d glyphs, line %d)"
          % (src, dst, atlas_w, atlas_h, len(glyphs), line_height))


if __name__ == "__main__":
    main()
