#!/usr/bin/env python3
"""docs/RANGI.txt (the user's approved rank list) -> src/ui/ranks.cpp.

    python tools/gen_ranks.py

Lines look like "1-1 | Egg on Legs | Jajko na nozkach", one per level, and the last one ("8-1+") is the single
maximum rank every level from 8-1 on carries. Regenerate after editing the list; the file is checked in.
"""
import os
import re
import sys

LINE = re.compile(r"^\s*(\d+)-(\d+)(\+?)\s*\|\s*(.+?)\s*\|\s*(.+?)\s*$")


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    src = os.path.join(root, "docs", "RANGI.txt")
    ranks, top = [], None
    for line in open(src, encoding="utf-8"):
        # the file ends with a "was -> is" table whose rows start with a level too; stop before it
        if line.startswith("====") and "BYLO" in line.upper().replace("Ł", "L"):
            break
        m = LINE.match(line)
        if not m or "->" in line:
            continue
        world, stage, plus, english, polish = m.groups()
        if plus:
            top = (english, polish)
        else:
            level = (int(world) - 1) * 5 + int(stage)
            if level != len(ranks) + 1:
                print(f"gen_ranks: {src} jumps from level {len(ranks)} to {world}-{stage}")
                return 1
            ranks.append((english, polish))
    if top is None or not ranks:
        print(f"gen_ranks: {src} has no ranks")
        return 1

    out = ['// generated by tools/gen_ranks.py from docs/RANGI.txt - do not edit', '#include "ui/ranks.h"', "",
           '#include "ui/lang.h"', "", "namespace cr {", "",
           "// { English, Polish } for levels 1-1 up (index = level - 1)",
           f"static const char *const kRanks[{len(ranks)}][2] = {{"]
    for english, polish in ranks:
        out.append(f'    {{"{english}", "{polish}"}},')
    out.append("};")
    out.append(f'static const char *const kTopRank[2] = {{"{top[0]}", "{top[1]}"}};')
    out.append("")
    out.append(f"int rankCount() {{ return {len(ranks)}; }}")
    out.append("")
    out.append("const char *rankName(int level)")
    out.append("{")
    out.append("    const int i = level - 1;")
    out.append(f"    return i < 0 ? kRanks[0][lang::current()] : i < {len(ranks)} ? kRanks[i][lang::current()]")
    out.append("                                                                 : kTopRank[lang::current()];")
    out.append("}")
    out.append("")
    out.append("} // namespace cr")
    dst = os.path.join(root, "src", "ui", "ranks.cpp")
    with open(dst, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print(f"gen_ranks: {len(ranks)} ranks + one maximum -> {dst}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
