#!/usr/bin/env python3
"""Generates the lookup tables of the SF2000 fixed-point code.

src/engine/fixed_tables.h: the sine table of the 16.16 maths (src/engine/fixed.h).
kSinQ16[i] = round(sin(2*pi*i/1024) * 65536) for i = 0..1024 (the extra entry makes interpolation branch free).
With linear interpolation between 1024 entries the worst error is ~(2*pi/1024)^2/8 = 4.7e-6, below one 16.16 step.

src/sw/sw_tables.h: the software renderer's light (src/sw/sw_math.cpp).
kLambertQ16[i] = round(((1.8 + i/256) / pi) ** (1/2.2) * 65536) for i = 0..256, the GLES shader's per-vertex term.

    python tools/gen_fixed_tables.py
"""
import math
import os

N = 1024
LAMBERT = 256


def write_lambert(root):
    out = os.path.join(root, "src", "sw", "sw_tables.h")
    values = [int(round(((1.8 + i / LAMBERT) / math.pi) ** (1 / 2.2) * 65536)) for i in range(LAMBERT + 1)]
    lines = [
        "// generated by tools/gen_fixed_tables.py - do not edit",
        "// ((1.8 + i/%d) / pi)^(1/2.2) in 16.16, i = 0..%d" % (LAMBERT, LAMBERT),
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace cr {",
        "namespace sw {",
        "",
        "static const int kLambertTableSize = %d;" % (LAMBERT + 1),
        "static const int32_t kLambertQ16[%d] = {" % (LAMBERT + 1),
    ]
    for i in range(0, LAMBERT + 1, 12):
        lines.append("    " + ", ".join(str(v) for v in values[i:i + 12]) + ",")
    lines += ["};", "", "} // namespace sw", "} // namespace cr", ""]
    with open(out, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print("gen_fixed_tables: %s (%d entries)" % (out, LAMBERT + 1))


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    write_lambert(root)
    out = os.path.join(root, "src", "engine", "fixed_tables.h")
    values = [int(round(math.sin(2 * math.pi * i / N) * 65536)) for i in range(N + 1)]
    lines = [
        "// generated by tools/gen_fixed_tables.py - do not edit",
        "// sin(2*pi*i/%d) in 16.16, i = 0..%d" % (N, N),
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace cr {",
        "",
        "static const int kSinTableBits = 10;",
        "static const int32_t kSinQ16[%d] = {" % (N + 1),
    ]
    for i in range(0, N + 1, 12):
        lines.append("    " + ", ".join(str(v) for v in values[i:i + 12]) + ",")
    lines += ["};", "", "} // namespace cr", ""]
    with open(out, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print("gen_fixed_tables: %s (%d entries)" % (out, N + 1))


if __name__ == "__main__":
    main()
