#!/usr/bin/env python3
"""Build the tiny metadata-only data set the Amiga game logic needs (task F1).

    python tools/make_amiga_meta.py [--data data_sf2000] [--out data_amiga]

WHY THIS EXISTS: the shared game logic needs model AABBs - Row/*.ts measures collision widths with
Math.round(box.max.x - box.min.x), so a car's width and a log's length come from the mesh bounds, not
from a table someone typed. But the Amiga never draws a mesh: it draws baked sprites. Shipping
data_sf2000/meshes just to read six floats per model would cost about a megabyte for roughly 800 bytes
of actual information.

src/engine/assets.cpp's loadFlatMesh reads the three counts BEFORE the AABB and every one of its bounds
checks passes at zero, so a mesh with no vertices, no triangles and no colours is a valid file. This
writes exactly that: a 40-byte stub carrying the real AABB bits, one per model. The bits are copied
verbatim, never re-encoded, because the SF2000/Amiga build turns them into 16.16 with realFromFloat
(bit twiddling, no float arithmetic) and a rounded value would move a collision box.

The result is that ModelLibrary::load works unmodified on the Amiga - no shared code changes at all,
so nothing about SF2000 or R36S can regress from this.

.fmesh layout (tools/bake_flat.py):
    0  'CRFM'
    4  u32 vertex_count, u32 triangle_count, u32 colour_count
   16  f32[3] aabbMin, f32[3] aabbMax
   40  ... payload (omitted here: all three counts are zero)
"""
import argparse
import os
import struct
import sys

HEADER_BYTES = 40
MAGIC = b"CRFM"


def read_aabb(path):
    with open(path, "rb") as f:
        head = f.read(HEADER_BYTES)
    if len(head) < HEADER_BYTES or head[:4] != MAGIC:
        return None
    # counts at 4..16 are deliberately ignored - only the bounds matter here
    return head[16:40]  # aabbMin + aabbMax, 6 little-endian floats, copied bit for bit


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default="data_sf2000", help="where the real .fmesh files are")
    ap.add_argument("--out", default="data_amiga")
    args = ap.parse_args()

    manifest_in = os.path.join(args.data, "manifest.txt")
    if not os.path.exists(manifest_in):
        sys.exit("no manifest at %s" % manifest_in)

    models = []
    extra_lines = []  # sound and music entries, copied in their original order - see the manifest note below
    with open(manifest_in, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            parts = line.split()
            if len(parts) >= 2 and parts[0] == "model":
                models.append(parts[1])
            elif len(parts) >= 2 and parts[0] in ("sound", "music"):
                extra_lines.append(line)
    if not models:
        sys.exit("no models listed in %s" % manifest_in)

    mesh_dir = os.path.join(args.out, "meshes")
    os.makedirs(mesh_dir, exist_ok=True)

    written, missing = 0, []
    for name in models:
        src = os.path.join(args.data, "meshes", name + ".fmesh")
        if not os.path.exists(src):
            missing.append(name)
            continue
        aabb = read_aabb(src)
        if aabb is None:
            missing.append(name)
            continue
        stub = MAGIC + struct.pack("<III", 0, 0, 0) + aabb
        assert len(stub) == HEADER_BYTES
        with open(os.path.join(mesh_dir, name + ".fmesh"), "wb") as f:
            f.write(stub)
        written += 1

    # The manifest the Amiga reads.
    #
    # It used to carry ONLY the models, on the reasoning that sounds and music "are named directly by the game
    # logic and never looked up here". That was wrong about music and it cost the port a feature: the console
    # versions pick tracks out of Manifest::music (apps/bobrhopper.cpp updateMusic - entry 0 is the menu song and
    # every new game takes the next one, cycling), so an empty list means one track can only ever loop forever,
    # which is exactly what the player heard. The music and sound lines are copied here verbatim, IN ORDER,
    # because that order is the rotation.
    with open(os.path.join(args.out, "manifest.txt"), "w", encoding="utf-8") as f:
        f.write("# generated by tools/make_amiga_meta.py - AABBs only, the Amiga draws baked sprites\n")
        for name in models:
            f.write("model %s %s %s\n" % (name, name, name))
        for line in extra_lines:
            f.write(line + "\n")

    total = written * HEADER_BYTES
    print("wrote %d stub meshes (%d bytes in total) + manifest -> %s" % (written, total, args.out))
    if missing:
        print("MISSING (no .fmesh found): %s" % ", ".join(missing))
        sys.exit(1)


if __name__ == "__main__":
    main()
