#!/usr/bin/env python3
"""Convert our baked font into the Amiga's own container (task G4).

    python tools/make_amiga_font.py [--data data_sf2000] [--sizes 12,16] [--out data_amiga]
                                    [--header src/amiga/font_ids.h]

WHY: the Amiga was drawing its status bar with a 5x7 font hand-coded in hud_bh.c. That was fine for
proving the bar renders at all, and wrong for shipping - the game has its own pixel font (retro.ttf,
"8BIT WONDER"), with Polish letters, and every other port of this game uses it. The user said so.

Input is what tools/bake_font.py produced (.fnt, LITTLE endian):
    char[4] 'CRF1'
    u16 atlas_w, atlas_h, pixel_size, line_height, glyph_count
    glyph_count x { u16 codepoint, u16 x, u16 y, u16 w, u16 h, i16 xoff, i16 yoff, u16 advance }
    atlas_w * atlas_h x u8 coverage (0 or 255), rows top-first

Output data_amiga/font.bhf, BIG endian so the 68k reads the tables where they lie:
     0  char[4] 'BHFN'
     4  u16 version (1), u16 face_count
     8  faces[face_count], 16 bytes each:
            u16 pixel_size, u16 line_height, u16 glyph_count, u16 atlas_w, u16 atlas_h,
            u16 reserved, u32 glyph_offset      (glyphs, then pixels, follow at that offset)
    ...  per face: glyph_count x { u16 codepoint, u16 x, u16 y, u16 w, u16 h, i16 xoff, i16 yoff, u16 advance }
    ...  per face: atlas_w * atlas_h bytes, 1 = ink, 0 = transparent

The coverage is collapsed from 0/255 to 0/1 on purpose: the font is a pixel font with no anti-aliasing, so
a byte per pixel carrying only ink/no-ink is all the information there is, and the blitter then needs no
threshold test in its inner loop - it draws the text colour wherever the byte is non-zero.
"""
import argparse
import os
import struct
import sys

MAGIC_IN = b"CRF1"
MAGIC_OUT = b"BHFN"
FACE_BYTES = 16
GLYPH_BYTES = 16


def load_fnt(path):
    with open(path, "rb") as f:
        data = f.read()
    if len(data) < 14 or data[:4] != MAGIC_IN:
        sys.exit("%s is not a CRF1 font" % path)
    atlas_w, atlas_h, pixel_size, line_height, count = struct.unpack("<HHHHH", data[4:14])
    at = 14
    glyphs = []
    for _ in range(count):
        cp, x, y, w, h, xoff, yoff, adv = struct.unpack("<HHHHHhhH", data[at:at + GLYPH_BYTES])
        glyphs.append((cp, x, y, w, h, xoff, yoff, adv))
        at += GLYPH_BYTES
    pixels = data[at:at + atlas_w * atlas_h]
    if len(pixels) < atlas_w * atlas_h:
        sys.exit("%s: atlas is short (%d of %d bytes)" % (path, len(pixels), atlas_w * atlas_h))
    return {"atlas_w": atlas_w, "atlas_h": atlas_h, "pixel_size": pixel_size,
            "line_height": line_height, "glyphs": glyphs, "pixels": pixels}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default="data_sf2000")
    ap.add_argument("--sizes", default="12,16", help="which baked sizes to ship")
    ap.add_argument("--out", default="data_amiga")
    ap.add_argument("--header", default="src/amiga/font_ids.h")
    ap.add_argument("--name", default="font.bhf", help="font640.bhf for the 640x480 set")
    args = ap.parse_args()

    sizes = [int(s) for s in args.sizes.split(",") if s.strip()]
    faces = []
    for size in sizes:
        path = os.path.join(args.data, "fonts", "retro_%d.fnt" % size)
        if not os.path.exists(path):
            sys.exit("missing %s - bake it first (tools/bake_font.py)" % path)
        face = load_fnt(path)
        faces.append(face)
        print("retro_%-3d  %3d glyphs, atlas %dx%d, line height %d"
              % (size, len(face["glyphs"]), face["atlas_w"], face["atlas_h"], face["line_height"]))

    header_bytes = 8 + FACE_BYTES * len(faces)
    offset = header_bytes
    bodies = []
    for face in faces:
        body = bytearray()
        for cp, x, y, w, h, xoff, yoff, adv in face["glyphs"]:
            body += struct.pack(">HHHHHhhH", cp, x, y, w, h, xoff, yoff, adv)
        # 0/255 coverage -> 0/1 ink
        body += bytes(1 if b else 0 for b in face["pixels"])
        bodies.append((offset, bytes(body)))
        offset += len(body)

    out = bytearray()
    out += MAGIC_OUT
    out += struct.pack(">HH", 1, len(faces))
    for face, (off, body) in zip(faces, bodies):
        out += struct.pack(">HHHHHHI", face["pixel_size"], face["line_height"], len(face["glyphs"]),
                           face["atlas_w"], face["atlas_h"], 0, off)
    for _, body in bodies:
        out += body

    os.makedirs(args.out, exist_ok=True)
    path = os.path.join(args.out, args.name)
    with open(path, "wb") as f:
        f.write(out)

    os.makedirs(os.path.dirname(args.header), exist_ok=True)
    with open(args.header, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/make_amiga_font.py - do not edit.\n")
        f.write("#ifndef BH_FONT_IDS_H\n#define BH_FONT_IDS_H\n\n")
        f.write("#define BH_FONT_FACES %d\n" % len(faces))
        for i, face in enumerate(faces):
            f.write("#define BH_FONT_%-4d %d  /* line height %d */\n"
                    % (face["pixel_size"], i, face["line_height"]))
        f.write("\n#endif\n")

    print("%d faces, %d bytes -> %s" % (len(faces), len(out), path))
    print("ids -> %s" % args.header)


if __name__ == "__main__":
    main()
