#!/usr/bin/env python3
"""Writes data/manifest.txt: one line per model, 'model <name> <mesh> <texture>'.
The engine loads meshes/<mesh>.mesh and textures/<texture>.tex for each model name the game asks for.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from assets_manifest import MODELS, MUSIC, SOUNDS, SOUNDS_EXTRA  # noqa: E402


def main(dst):
    with open(dst, "w", encoding="ascii", newline="\n") as f:
        f.write("# generated by tools/write_manifest.py\n")
        for name in sorted(MODELS):
            mesh, tex = MODELS[name]
            f.write(f"model {name} {mesh} {tex}\n")
        sounds = dict(SOUNDS, **SOUNDS_EXTRA)
        for name in sorted(sounds):
            f.write(f"sound {name}\n")
        for name in MUSIC:  # order matters: title first, then the game tracks
            f.write(f"music {name}\n")
    print(f"manifest: {len(MODELS)} models, {len(sounds)} sounds, {len(MUSIC)} music -> {dst}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "data/manifest.txt")
