/* Generated by tools/gen_ehb_data.py from the "sat20" EHB assets
 * (saturation x1.2).  DO NOT EDIT BY HAND - re-run the generator.
 *
 * See docs/LORES-GRAPHICS-PLAN.md and the report accompanying the EHB work for
 * what these tables mean and what the reduction costs.
 *
 * 7 of the 64 EHB entries have no pre-image in the 256-colour palette.
 *
 * Three translation units need these tables (spritecache.cpp applies the
 * reduction, gfx.cpp remaps text colours, video/amiga_v.cpp loads the colour
 * registers), so the header DECLARES them and exactly one TU defines them by
 * doing
 *     #define AMIGA_EHB_DATA_DEFINE
 * before the include.  spritecache.cpp is that TU.  Emitting them as "static
 * const" instead would put three copies of 512 bytes in the binary, and on this
 * target every kilobyte is LoadSeg'd into RAM before the game starts.
 */

#ifndef AMIGA_EHB_DATA_H
#define AMIGA_EHB_DATA_H

/** TTD palette index -> EHB index (0..63).  Index 0 stays transparent. */
extern const unsigned char _amiga_ehb_remap[256];

/** EHB index -> representative TTD palette index mapping to it. */
extern const unsigned char _amiga_ehb_rep[64];

/** 64 x RGB8, loaded into colour registers 0..63. */
extern const unsigned char _amiga_ehb_palette[64 * 3];

#endif /* AMIGA_EHB_DATA_H */

#ifdef AMIGA_EHB_DATA_DEFINE
#ifndef AMIGA_EHB_DATA_DEFINED
#define AMIGA_EHB_DATA_DEFINED

const unsigned char _amiga_ehb_remap[256] = {
	   0,   38,   38,   38,   37,   35,   34,   33,   33,    5,    3,    3,    4,    2,    2,    1,
	  38,   37,   36,    6,    5,    5,    3,    4,   44,   44,   50,   46,   47,   18,   18,   22,
	  44,   43,   45,   12,   47,   18,   22,    2,   39,   39,   41,    7,    7,   10,   10,   11,
	  11,    2,   14,   15,   15,   44,   43,   45,   47,   18,   18,   16,   39,   42,   43,   12,
	  10,   13,   13,   14,   15,   15,   40,   39,   42,   42,    7,    7,   12,   10,   11,   11,
	  51,   51,   51,   52,   52,   19,   19,   19,   51,   51,   50,   48,   47,   18,   18,   16,
	  51,   51,   48,   48,   47,   18,   22,   22,   40,   39,   44,   42,   43,   45,   12,   12,
	  44,   42,   43,   12,   12,   10,   11,   11,   11,   13,   42,   42,   43,    7,   12,   30,
	  55,   38,   60,   60,   36,   30,    3,    4,   59,   63,   27,   27,   27,   31,   31,   29,
	  59,   59,   58,   27,   27,   26,   26,   25,   24,    4,   58,   57,   56,   23,    6,   25,
	  24,   21,    7,    9,    9,   11,   11,    2,    2,    1,   63,   63,   27,   31,   31,   29,
	  29,    4,   39,   39,   41,    7,    7,    9,    9,   10,   11,   11,   13,   13,   14,   15,
	  11,   11,   13,   13,   13,    2,   59,   59,   58,   58,   27,   26,   26,   25,   19,   19,
	  20,   20,   21,   21,    4,   24,   25,   40,    8,   56,   56,   23,   23,   23,   25,   25,
	  24,    4,   21,   32,   32,   32,   32,   32,    9,   10,   11,   11,   11,   13,   13,    9,
	   9,   32,   32,   32,   17,    5,   56,   23,   23,   23,   25,   25,   24,    4,   21,    1,
};

const unsigned char _amiga_ehb_rep[64] = {
	   0,   15,   13,   10,  135,   21,   19,  162,  216,  184,  185,  118,  116,  195,   50,   52,
	  95,  244,   94,  206,  209,  210,  103,  248,  152,  159,  150,  202,   28,  175,  133,  174,
	 227,    7,    6,    5,   18,   17,   16,   71,  215,  180,   61,  114,   25,   55,   27,   28,
	  91,   49,   90,   82,   84,   53,   54,  128,  156,  155,  200,  199,  130,   61,   62,  171,
};

const unsigned char _amiga_ehb_palette[64 * 3] = {
	  0,   0,   0, 255, 255, 255, 221, 221, 221, 170, 170, 170,
	204, 221, 238, 136, 153, 170, 102, 119, 153, 153,  51,  51,
	 34,  34,  34, 255,  17,   0, 221,  85,  17, 238, 136,  85,
	153, 102,  51, 255, 187,  34, 221, 204,  68, 255, 255, 136,
	187, 204, 102, 204, 238,  85, 153, 170, 119,  85, 153,  34,
	136, 238,  85, 221, 238, 238, 187, 204, 204,  34, 119, 136,
	119, 204, 238, 102, 170, 204,  51, 136, 238,  51,  85, 204,
	119, 136, 238, 187, 187, 204, 136, 136, 153, 170, 119, 238,
	  0,   0,   0, 119, 119, 119, 102, 102, 102,  85,  85,  85,
	102, 102, 119,  68,  68,  85,  51,  51,  68,  68,  17,  17,
	 17,  17,  17, 119,   0,   0, 102,  34,   0, 119,  68,  34,
	 68,  51,  17, 119,  85,  17, 102, 102,  34, 119, 119,  68,
	 85, 102,  51, 102, 119,  34,  68,  85,  51,  34,  68,  17,
	 68, 119,  34, 102, 119, 119,  85, 102, 102,  17,  51,  68,
	 51, 102, 119,  51,  85, 102,  17,  68, 119,  17,  34, 102,
	 51,  68, 119,  85,  85, 102,  68,  68,  68,  85,  51, 119,
};

#endif /* AMIGA_EHB_DATA_DEFINED */
#endif /* AMIGA_EHB_DATA_DEFINE */
