// Generated by tools/make_amiga_font.py - do not edit.
#ifndef BH_FONT_IDS_H
#define BH_FONT_IDS_H

#define BH_FONT_FACES 4
#define BH_FONT_6    0  /* line height 6 */
#define BH_FONT_7    1  /* line height 7 */
#define BH_FONT_9    2  /* line height 9 */
#define BH_FONT_16   3  /* line height 16 */

#endif
