// Generated by tools/make_amiga_audio.py - do not edit.
// Sound ids, so the game never looks a sound up by name while it is running.
#ifndef BH_SOUND_IDS_H
#define BH_SOUND_IDS_H

#define BH_SOUND_COUNT 34
#define BH_SOUND_PERIOD 161  /* PAL Paula: 22050 Hz */

#define SND_BANNER                         0
#define SND_BEAVER_DIE_0                   1
#define SND_BEAVER_DIE_1                   2
#define SND_BEAVER_MOVE_0                  3
#define SND_BEAVER_MOVE_1                  4
#define SND_BEAVER_TAIL_SLAP               5
#define SND_BUTTON_IN                      6
#define SND_BUTTON_OUT                     7
#define SND_CAR_DIE_0                      8
#define SND_CAR_DIE_1                      9
#define SND_CAR_PASSIVE_1                  10
#define SND_CHICKEN_DIE_0                  11
#define SND_CHICKEN_DIE_1                  12
#define SND_CHICKEN_MOVE_0                 13
#define SND_CHICKEN_MOVE_1                 14
#define SND_CHICKEN_MOVE_10                15
#define SND_CHICKEN_MOVE_11                16
#define SND_CHICKEN_MOVE_2                 17
#define SND_CHICKEN_MOVE_3                 18
#define SND_CHICKEN_MOVE_4                 19
#define SND_CHICKEN_MOVE_5                 20
#define SND_CHICKEN_MOVE_6                 21
#define SND_CHICKEN_MOVE_7                 22
#define SND_CHICKEN_MOVE_8                 23
#define SND_CHICKEN_MOVE_9                 24
#define SND_FANFARE                        25
#define SND_FANFARE_0                      26
#define SND_FANFARE_1                      27
#define SND_FANFARE_2                      28
#define SND_TRAIN_ALARM                    29
#define SND_TRAIN_DIE_0                    30
#define SND_TRAIN_MOVE_0                   31
#define SND_TRAIN_MOVE_1                   32
#define SND_WATER                          33

typedef struct { const char *name; short id; } BHSoundName;
/* Include from exactly ONE translation unit. */
static const BHSoundName bh_sound_names[] = {
    {"banner", 0},
    {"beaver_die_0", 1},
    {"beaver_die_1", 2},
    {"beaver_move_0", 3},
    {"beaver_move_1", 4},
    {"beaver_tail_slap", 5},
    {"button_in", 6},
    {"button_out", 7},
    {"car_die_0", 8},
    {"car_die_1", 9},
    {"car_passive_1", 10},
    {"chicken_die_0", 11},
    {"chicken_die_1", 12},
    {"chicken_move_0", 13},
    {"chicken_move_1", 14},
    {"chicken_move_10", 15},
    {"chicken_move_11", 16},
    {"chicken_move_2", 17},
    {"chicken_move_3", 18},
    {"chicken_move_4", 19},
    {"chicken_move_5", 20},
    {"chicken_move_6", 21},
    {"chicken_move_7", 22},
    {"chicken_move_8", 23},
    {"chicken_move_9", 24},
    {"fanfare", 25},
    {"fanfare_0", 26},
    {"fanfare_1", 27},
    {"fanfare_2", 28},
    {"train_alarm", 29},
    {"train_die_0", 30},
    {"train_move_0", 31},
    {"train_move_1", 32},
    {"water", 33},
};
#define BH_SOUND_NAME_COUNT 34

#endif
