// Generated by tools/pack_amiga_sprites.py - do not edit.
// One constant per baked sprite, so the Amiga never looks a sprite up by name at runtime.
#ifndef BH_SPRITE_IDS_H
#define BH_SPRITE_IDS_H

#define BH_SPRITE_COUNT 371
#define BH_PALETTE_ENTRIES 170
// Palette index 0 is the transparent key and is never drawn; index 1 is the sky (0x87C6FF from
// src/game/settings.h), which appears in no sprite and must therefore be reserved on purpose.
#define BH_SKY_INDEX 1

#define SPR_BEAVER_R0_S0                         0
#define SPR_BEAVER_R0_S1                         1
#define SPR_BEAVER_R0_S2                         2
#define SPR_BEAVER_R0_S3                         3
#define SPR_BEAVER_R0_S4                         4
#define SPR_BEAVER_R0_S5                         5
#define SPR_BEAVER_R0_S6                         6
#define SPR_BEAVER_R0_S7                         7
#define SPR_BEAVER_R0_S8                         8
#define SPR_BEAVER_R0_S9                         9
#define SPR_BEAVER_R0_S10                        10
#define SPR_BEAVER_R1_S0                         11
#define SPR_BEAVER_R1_S1                         12
#define SPR_BEAVER_R1_S2                         13
#define SPR_BEAVER_R1_S3                         14
#define SPR_BEAVER_R1_S4                         15
#define SPR_BEAVER_R1_S5                         16
#define SPR_BEAVER_R1_S6                         17
#define SPR_BEAVER_R1_S7                         18
#define SPR_BEAVER_R1_S8                         19
#define SPR_BEAVER_R1_S9                         20
#define SPR_BEAVER_R1_S10                        21
#define SPR_BEAVER_R2_S0                         22
#define SPR_BEAVER_R2_S1                         23
#define SPR_BEAVER_R2_S2                         24
#define SPR_BEAVER_R2_S3                         25
#define SPR_BEAVER_R2_S4                         26
#define SPR_BEAVER_R2_S5                         27
#define SPR_BEAVER_R2_S6                         28
#define SPR_BEAVER_R2_S7                         29
#define SPR_BEAVER_R2_S8                         30
#define SPR_BEAVER_R2_S9                         31
#define SPR_BEAVER_R2_S10                        32
#define SPR_BEAVER_R3_S0                         33
#define SPR_BEAVER_R3_S1                         34
#define SPR_BEAVER_R3_S2                         35
#define SPR_BEAVER_R3_S3                         36
#define SPR_BEAVER_R3_S4                         37
#define SPR_BEAVER_R3_S5                         38
#define SPR_BEAVER_R3_S6                         39
#define SPR_BEAVER_R3_S7                         40
#define SPR_BEAVER_R3_S8                         41
#define SPR_BEAVER_R3_S9                         42
#define SPR_BEAVER_R3_S10                        43
#define SPR_BEAVER_R4_S0                         44
#define SPR_BEAVER_R4_S1                         45
#define SPR_BEAVER_R4_S2                         46
#define SPR_BEAVER_R4_S3                         47
#define SPR_BEAVER_R4_S4                         48
#define SPR_BEAVER_R4_S5                         49
#define SPR_BEAVER_R4_S6                         50
#define SPR_BEAVER_R4_S7                         51
#define SPR_BEAVER_R4_S8                         52
#define SPR_BEAVER_R4_S9                         53
#define SPR_BEAVER_R4_S10                        54
#define SPR_BEAVER_R5_S0                         55
#define SPR_BEAVER_R5_S1                         56
#define SPR_BEAVER_R5_S2                         57
#define SPR_BEAVER_R5_S3                         58
#define SPR_BEAVER_R5_S4                         59
#define SPR_BEAVER_R5_S5                         60
#define SPR_BEAVER_R5_S6                         61
#define SPR_BEAVER_R5_S7                         62
#define SPR_BEAVER_R5_S8                         63
#define SPR_BEAVER_R5_S9                         64
#define SPR_BEAVER_R5_S10                        65
#define SPR_BEAVER_R6_S0                         66
#define SPR_BEAVER_R6_S1                         67
#define SPR_BEAVER_R6_S2                         68
#define SPR_BEAVER_R6_S3                         69
#define SPR_BEAVER_R6_S4                         70
#define SPR_BEAVER_R6_S5                         71
#define SPR_BEAVER_R6_S6                         72
#define SPR_BEAVER_R6_S7                         73
#define SPR_BEAVER_R6_S8                         74
#define SPR_BEAVER_R6_S9                         75
#define SPR_BEAVER_R6_S10                        76
#define SPR_BEAVER_R7_S0                         77
#define SPR_BEAVER_R7_S1                         78
#define SPR_BEAVER_R7_S2                         79
#define SPR_BEAVER_R7_S3                         80
#define SPR_BEAVER_R7_S4                         81
#define SPR_BEAVER_R7_S5                         82
#define SPR_BEAVER_R7_S6                         83
#define SPR_BEAVER_R7_S7                         84
#define SPR_BEAVER_R7_S8                         85
#define SPR_BEAVER_R7_S9                         86
#define SPR_BEAVER_R7_S10                        87
#define SPR_BEAVER_R8_S0                         88
#define SPR_BEAVER_R8_S1                         89
#define SPR_BEAVER_R8_S2                         90
#define SPR_BEAVER_R8_S3                         91
#define SPR_BEAVER_R8_S4                         92
#define SPR_BEAVER_R8_S5                         93
#define SPR_BEAVER_R8_S6                         94
#define SPR_BEAVER_R8_S7                         95
#define SPR_BEAVER_R8_S8                         96
#define SPR_BEAVER_R8_S9                         97
#define SPR_BEAVER_R8_S10                        98
#define SPR_BEAVER_R9_S0                         99
#define SPR_BEAVER_R9_S1                         100
#define SPR_BEAVER_R9_S2                         101
#define SPR_BEAVER_R9_S3                         102
#define SPR_BEAVER_R9_S4                         103
#define SPR_BEAVER_R9_S5                         104
#define SPR_BEAVER_R9_S6                         105
#define SPR_BEAVER_R9_S7                         106
#define SPR_BEAVER_R9_S8                         107
#define SPR_BEAVER_R9_S9                         108
#define SPR_BEAVER_R9_S10                        109
#define SPR_BEAVER_R10_S0                        110
#define SPR_BEAVER_R10_S1                        111
#define SPR_BEAVER_R10_S2                        112
#define SPR_BEAVER_R10_S3                        113
#define SPR_BEAVER_R10_S4                        114
#define SPR_BEAVER_R10_S5                        115
#define SPR_BEAVER_R10_S6                        116
#define SPR_BEAVER_R10_S7                        117
#define SPR_BEAVER_R10_S8                        118
#define SPR_BEAVER_R10_S9                        119
#define SPR_BEAVER_R10_S10                       120
#define SPR_BEAVER_R11_S0                        121
#define SPR_BEAVER_R11_S1                        122
#define SPR_BEAVER_R11_S2                        123
#define SPR_BEAVER_R11_S3                        124
#define SPR_BEAVER_R11_S4                        125
#define SPR_BEAVER_R11_S5                        126
#define SPR_BEAVER_R11_S6                        127
#define SPR_BEAVER_R11_S7                        128
#define SPR_BEAVER_R11_S8                        129
#define SPR_BEAVER_R11_S9                        130
#define SPR_BEAVER_R11_S10                       131
#define SPR_BLUE_CAR_R0                          132
#define SPR_BLUE_CAR_R1                          133
#define SPR_BLUE_CAR_R2                          134
#define SPR_BLUE_CAR_R3                          135
#define SPR_BLUE_TRUCK_R0                        136
#define SPR_BLUE_TRUCK_R1                        137
#define SPR_BLUE_TRUCK_R2                        138
#define SPR_BLUE_TRUCK_R3                        139
#define SPR_BOULDER_0_R0                         140
#define SPR_BOULDER_0_R1                         141
#define SPR_BOULDER_0_R2                         142
#define SPR_BOULDER_0_R3                         143
#define SPR_BOULDER_1_R0                         144
#define SPR_BOULDER_1_R1                         145
#define SPR_BOULDER_1_R2                         146
#define SPR_BOULDER_1_R3                         147
#define SPR_CHICKEN_R0_S0                        148
#define SPR_CHICKEN_R0_S1                        149
#define SPR_CHICKEN_R0_S2                        150
#define SPR_CHICKEN_R0_S3                        151
#define SPR_CHICKEN_R0_S4                        152
#define SPR_CHICKEN_R0_S5                        153
#define SPR_CHICKEN_R0_S6                        154
#define SPR_CHICKEN_R0_S7                        155
#define SPR_CHICKEN_R0_S8                        156
#define SPR_CHICKEN_R0_S9                        157
#define SPR_CHICKEN_R0_S10                       158
#define SPR_CHICKEN_R1_S0                        159
#define SPR_CHICKEN_R1_S1                        160
#define SPR_CHICKEN_R1_S2                        161
#define SPR_CHICKEN_R1_S3                        162
#define SPR_CHICKEN_R1_S4                        163
#define SPR_CHICKEN_R1_S5                        164
#define SPR_CHICKEN_R1_S6                        165
#define SPR_CHICKEN_R1_S7                        166
#define SPR_CHICKEN_R1_S8                        167
#define SPR_CHICKEN_R1_S9                        168
#define SPR_CHICKEN_R1_S10                       169
#define SPR_CHICKEN_R2_S0                        170
#define SPR_CHICKEN_R2_S1                        171
#define SPR_CHICKEN_R2_S2                        172
#define SPR_CHICKEN_R2_S3                        173
#define SPR_CHICKEN_R2_S4                        174
#define SPR_CHICKEN_R2_S5                        175
#define SPR_CHICKEN_R2_S6                        176
#define SPR_CHICKEN_R2_S7                        177
#define SPR_CHICKEN_R2_S8                        178
#define SPR_CHICKEN_R2_S9                        179
#define SPR_CHICKEN_R2_S10                       180
#define SPR_CHICKEN_R3_S0                        181
#define SPR_CHICKEN_R3_S1                        182
#define SPR_CHICKEN_R3_S2                        183
#define SPR_CHICKEN_R3_S3                        184
#define SPR_CHICKEN_R3_S4                        185
#define SPR_CHICKEN_R3_S5                        186
#define SPR_CHICKEN_R3_S6                        187
#define SPR_CHICKEN_R3_S7                        188
#define SPR_CHICKEN_R3_S8                        189
#define SPR_CHICKEN_R3_S9                        190
#define SPR_CHICKEN_R3_S10                       191
#define SPR_CHICKEN_R4_S0                        192
#define SPR_CHICKEN_R4_S1                        193
#define SPR_CHICKEN_R4_S2                        194
#define SPR_CHICKEN_R4_S3                        195
#define SPR_CHICKEN_R4_S4                        196
#define SPR_CHICKEN_R4_S5                        197
#define SPR_CHICKEN_R4_S6                        198
#define SPR_CHICKEN_R4_S7                        199
#define SPR_CHICKEN_R4_S8                        200
#define SPR_CHICKEN_R4_S9                        201
#define SPR_CHICKEN_R4_S10                       202
#define SPR_CHICKEN_R5_S0                        203
#define SPR_CHICKEN_R5_S1                        204
#define SPR_CHICKEN_R5_S2                        205
#define SPR_CHICKEN_R5_S3                        206
#define SPR_CHICKEN_R5_S4                        207
#define SPR_CHICKEN_R5_S5                        208
#define SPR_CHICKEN_R5_S6                        209
#define SPR_CHICKEN_R5_S7                        210
#define SPR_CHICKEN_R5_S8                        211
#define SPR_CHICKEN_R5_S9                        212
#define SPR_CHICKEN_R5_S10                       213
#define SPR_CHICKEN_R6_S0                        214
#define SPR_CHICKEN_R6_S1                        215
#define SPR_CHICKEN_R6_S2                        216
#define SPR_CHICKEN_R6_S3                        217
#define SPR_CHICKEN_R6_S4                        218
#define SPR_CHICKEN_R6_S5                        219
#define SPR_CHICKEN_R6_S6                        220
#define SPR_CHICKEN_R6_S7                        221
#define SPR_CHICKEN_R6_S8                        222
#define SPR_CHICKEN_R6_S9                        223
#define SPR_CHICKEN_R6_S10                       224
#define SPR_CHICKEN_R7_S0                        225
#define SPR_CHICKEN_R7_S1                        226
#define SPR_CHICKEN_R7_S2                        227
#define SPR_CHICKEN_R7_S3                        228
#define SPR_CHICKEN_R7_S4                        229
#define SPR_CHICKEN_R7_S5                        230
#define SPR_CHICKEN_R7_S6                        231
#define SPR_CHICKEN_R7_S7                        232
#define SPR_CHICKEN_R7_S8                        233
#define SPR_CHICKEN_R7_S9                        234
#define SPR_CHICKEN_R7_S10                       235
#define SPR_CHICKEN_R8_S0                        236
#define SPR_CHICKEN_R8_S1                        237
#define SPR_CHICKEN_R8_S2                        238
#define SPR_CHICKEN_R8_S3                        239
#define SPR_CHICKEN_R8_S4                        240
#define SPR_CHICKEN_R8_S5                        241
#define SPR_CHICKEN_R8_S6                        242
#define SPR_CHICKEN_R8_S7                        243
#define SPR_CHICKEN_R8_S8                        244
#define SPR_CHICKEN_R8_S9                        245
#define SPR_CHICKEN_R8_S10                       246
#define SPR_CHICKEN_R9_S0                        247
#define SPR_CHICKEN_R9_S1                        248
#define SPR_CHICKEN_R9_S2                        249
#define SPR_CHICKEN_R9_S3                        250
#define SPR_CHICKEN_R9_S4                        251
#define SPR_CHICKEN_R9_S5                        252
#define SPR_CHICKEN_R9_S6                        253
#define SPR_CHICKEN_R9_S7                        254
#define SPR_CHICKEN_R9_S8                        255
#define SPR_CHICKEN_R9_S9                        256
#define SPR_CHICKEN_R9_S10                       257
#define SPR_CHICKEN_R10_S0                       258
#define SPR_CHICKEN_R10_S1                       259
#define SPR_CHICKEN_R10_S2                       260
#define SPR_CHICKEN_R10_S3                       261
#define SPR_CHICKEN_R10_S4                       262
#define SPR_CHICKEN_R10_S5                       263
#define SPR_CHICKEN_R10_S6                       264
#define SPR_CHICKEN_R10_S7                       265
#define SPR_CHICKEN_R10_S8                       266
#define SPR_CHICKEN_R10_S9                       267
#define SPR_CHICKEN_R10_S10                      268
#define SPR_CHICKEN_R11_S0                       269
#define SPR_CHICKEN_R11_S1                       270
#define SPR_CHICKEN_R11_S2                       271
#define SPR_CHICKEN_R11_S3                       272
#define SPR_CHICKEN_R11_S4                       273
#define SPR_CHICKEN_R11_S5                       274
#define SPR_CHICKEN_R11_S6                       275
#define SPR_CHICKEN_R11_S7                       276
#define SPR_CHICKEN_R11_S8                       277
#define SPR_CHICKEN_R11_S9                       278
#define SPR_CHICKEN_R11_S10                      279
#define SPR_GRASS_0_R0                           280
#define SPR_GRASS_1_R0                           281
#define SPR_GREEN_CAR_R0                         282
#define SPR_GREEN_CAR_R1                         283
#define SPR_GREEN_CAR_R2                         284
#define SPR_GREEN_CAR_R3                         285
#define SPR_LILY_PAD_R0                          286
#define SPR_LILY_PAD_R1                          287
#define SPR_LILY_PAD_R2                          288
#define SPR_LILY_PAD_R3                          289
#define SPR_LOG_0_R0                             290
#define SPR_LOG_0_R1                             291
#define SPR_LOG_0_R2                             292
#define SPR_LOG_0_R3                             293
#define SPR_LOG_1_R0                             294
#define SPR_LOG_1_R1                             295
#define SPR_LOG_1_R2                             296
#define SPR_LOG_1_R3                             297
#define SPR_LOG_2_R0                             298
#define SPR_LOG_2_R1                             299
#define SPR_LOG_2_R2                             300
#define SPR_LOG_2_R3                             301
#define SPR_LOG_3_R0                             302
#define SPR_LOG_3_R1                             303
#define SPR_LOG_3_R2                             304
#define SPR_LOG_3_R3                             305
#define SPR_ORANGE_CAR_R0                        306
#define SPR_ORANGE_CAR_R1                        307
#define SPR_ORANGE_CAR_R2                        308
#define SPR_ORANGE_CAR_R3                        309
#define SPR_POLICE_CAR_R0                        310
#define SPR_POLICE_CAR_R1                        311
#define SPR_POLICE_CAR_R2                        312
#define SPR_POLICE_CAR_R3                        313
#define SPR_PURPLE_CAR_R0                        314
#define SPR_PURPLE_CAR_R1                        315
#define SPR_PURPLE_CAR_R2                        316
#define SPR_PURPLE_CAR_R3                        317
#define SPR_RAILROAD_R0                          318
#define SPR_RED_TRUCK_R0                         319
#define SPR_RED_TRUCK_R1                         320
#define SPR_RED_TRUCK_R2                         321
#define SPR_RED_TRUCK_R3                         322
#define SPR_RIVER_R0                             323
#define SPR_ROAD_0_R0                            324
#define SPR_ROAD_1_R0                            325
#define SPR_TAXI_R0                              326
#define SPR_TAXI_R1                              327
#define SPR_TAXI_R2                              328
#define SPR_TAXI_R3                              329
#define SPR_TRAIN_BACK_R0                        330
#define SPR_TRAIN_BACK_R1                        331
#define SPR_TRAIN_BACK_R2                        332
#define SPR_TRAIN_BACK_R3                        333
#define SPR_TRAIN_FRONT_R0                       334
#define SPR_TRAIN_FRONT_R1                       335
#define SPR_TRAIN_FRONT_R2                       336
#define SPR_TRAIN_FRONT_R3                       337
#define SPR_TRAIN_LIGHT_ACTIVE_0_R0              338
#define SPR_TRAIN_LIGHT_ACTIVE_0_R1              339
#define SPR_TRAIN_LIGHT_ACTIVE_0_R2              340
#define SPR_TRAIN_LIGHT_ACTIVE_0_R3              341
#define SPR_TRAIN_LIGHT_ACTIVE_1_R0              342
#define SPR_TRAIN_LIGHT_ACTIVE_1_R1              343
#define SPR_TRAIN_LIGHT_ACTIVE_1_R2              344
#define SPR_TRAIN_LIGHT_ACTIVE_1_R3              345
#define SPR_TRAIN_LIGHT_INACTIVE_R0              346
#define SPR_TRAIN_LIGHT_INACTIVE_R1              347
#define SPR_TRAIN_LIGHT_INACTIVE_R2              348
#define SPR_TRAIN_LIGHT_INACTIVE_R3              349
#define SPR_TRAIN_MIDDLE_R0                      350
#define SPR_TRAIN_MIDDLE_R1                      351
#define SPR_TRAIN_MIDDLE_R2                      352
#define SPR_TRAIN_MIDDLE_R3                      353
#define SPR_TREE_0_R0                            354
#define SPR_TREE_0_R1                            355
#define SPR_TREE_0_R2                            356
#define SPR_TREE_0_R3                            357
#define SPR_TREE_1_R0                            358
#define SPR_TREE_1_R1                            359
#define SPR_TREE_1_R2                            360
#define SPR_TREE_1_R3                            361
#define SPR_TREE_2_R0                            362
#define SPR_TREE_2_R1                            363
#define SPR_TREE_2_R2                            364
#define SPR_TREE_2_R3                            365
#define SPR_TREE_3_R0                            366
#define SPR_TREE_3_R1                            367
#define SPR_TREE_3_R2                            368
#define SPR_TREE_3_R3                            369
#define SPR_LOGO_R0                              370

typedef struct {
    const char *name;
    short rot;   /* 0..BH_ROT_MAX-1, in equal steps about Y; the count is PER MODEL */
    short phase; /* squash phase for the hero, -1 for everything else */
    short id;
} BHSpriteName;

/* Include this header from exactly ONE translation unit if you want the table. */
static const BHSpriteName bh_sprite_names[] = {
    {"beaver", 0, 0, 0},
    {"beaver", 0, 1, 1},
    {"beaver", 0, 2, 2},
    {"beaver", 0, 3, 3},
    {"beaver", 0, 4, 4},
    {"beaver", 0, 5, 5},
    {"beaver", 0, 6, 6},
    {"beaver", 0, 7, 7},
    {"beaver", 0, 8, 8},
    {"beaver", 0, 9, 9},
    {"beaver", 0, 10, 10},
    {"beaver", 1, 0, 11},
    {"beaver", 1, 1, 12},
    {"beaver", 1, 2, 13},
    {"beaver", 1, 3, 14},
    {"beaver", 1, 4, 15},
    {"beaver", 1, 5, 16},
    {"beaver", 1, 6, 17},
    {"beaver", 1, 7, 18},
    {"beaver", 1, 8, 19},
    {"beaver", 1, 9, 20},
    {"beaver", 1, 10, 21},
    {"beaver", 2, 0, 22},
    {"beaver", 2, 1, 23},
    {"beaver", 2, 2, 24},
    {"beaver", 2, 3, 25},
    {"beaver", 2, 4, 26},
    {"beaver", 2, 5, 27},
    {"beaver", 2, 6, 28},
    {"beaver", 2, 7, 29},
    {"beaver", 2, 8, 30},
    {"beaver", 2, 9, 31},
    {"beaver", 2, 10, 32},
    {"beaver", 3, 0, 33},
    {"beaver", 3, 1, 34},
    {"beaver", 3, 2, 35},
    {"beaver", 3, 3, 36},
    {"beaver", 3, 4, 37},
    {"beaver", 3, 5, 38},
    {"beaver", 3, 6, 39},
    {"beaver", 3, 7, 40},
    {"beaver", 3, 8, 41},
    {"beaver", 3, 9, 42},
    {"beaver", 3, 10, 43},
    {"beaver", 4, 0, 44},
    {"beaver", 4, 1, 45},
    {"beaver", 4, 2, 46},
    {"beaver", 4, 3, 47},
    {"beaver", 4, 4, 48},
    {"beaver", 4, 5, 49},
    {"beaver", 4, 6, 50},
    {"beaver", 4, 7, 51},
    {"beaver", 4, 8, 52},
    {"beaver", 4, 9, 53},
    {"beaver", 4, 10, 54},
    {"beaver", 5, 0, 55},
    {"beaver", 5, 1, 56},
    {"beaver", 5, 2, 57},
    {"beaver", 5, 3, 58},
    {"beaver", 5, 4, 59},
    {"beaver", 5, 5, 60},
    {"beaver", 5, 6, 61},
    {"beaver", 5, 7, 62},
    {"beaver", 5, 8, 63},
    {"beaver", 5, 9, 64},
    {"beaver", 5, 10, 65},
    {"beaver", 6, 0, 66},
    {"beaver", 6, 1, 67},
    {"beaver", 6, 2, 68},
    {"beaver", 6, 3, 69},
    {"beaver", 6, 4, 70},
    {"beaver", 6, 5, 71},
    {"beaver", 6, 6, 72},
    {"beaver", 6, 7, 73},
    {"beaver", 6, 8, 74},
    {"beaver", 6, 9, 75},
    {"beaver", 6, 10, 76},
    {"beaver", 7, 0, 77},
    {"beaver", 7, 1, 78},
    {"beaver", 7, 2, 79},
    {"beaver", 7, 3, 80},
    {"beaver", 7, 4, 81},
    {"beaver", 7, 5, 82},
    {"beaver", 7, 6, 83},
    {"beaver", 7, 7, 84},
    {"beaver", 7, 8, 85},
    {"beaver", 7, 9, 86},
    {"beaver", 7, 10, 87},
    {"beaver", 8, 0, 88},
    {"beaver", 8, 1, 89},
    {"beaver", 8, 2, 90},
    {"beaver", 8, 3, 91},
    {"beaver", 8, 4, 92},
    {"beaver", 8, 5, 93},
    {"beaver", 8, 6, 94},
    {"beaver", 8, 7, 95},
    {"beaver", 8, 8, 96},
    {"beaver", 8, 9, 97},
    {"beaver", 8, 10, 98},
    {"beaver", 9, 0, 99},
    {"beaver", 9, 1, 100},
    {"beaver", 9, 2, 101},
    {"beaver", 9, 3, 102},
    {"beaver", 9, 4, 103},
    {"beaver", 9, 5, 104},
    {"beaver", 9, 6, 105},
    {"beaver", 9, 7, 106},
    {"beaver", 9, 8, 107},
    {"beaver", 9, 9, 108},
    {"beaver", 9, 10, 109},
    {"beaver", 10, 0, 110},
    {"beaver", 10, 1, 111},
    {"beaver", 10, 2, 112},
    {"beaver", 10, 3, 113},
    {"beaver", 10, 4, 114},
    {"beaver", 10, 5, 115},
    {"beaver", 10, 6, 116},
    {"beaver", 10, 7, 117},
    {"beaver", 10, 8, 118},
    {"beaver", 10, 9, 119},
    {"beaver", 10, 10, 120},
    {"beaver", 11, 0, 121},
    {"beaver", 11, 1, 122},
    {"beaver", 11, 2, 123},
    {"beaver", 11, 3, 124},
    {"beaver", 11, 4, 125},
    {"beaver", 11, 5, 126},
    {"beaver", 11, 6, 127},
    {"beaver", 11, 7, 128},
    {"beaver", 11, 8, 129},
    {"beaver", 11, 9, 130},
    {"beaver", 11, 10, 131},
    {"blue_car", 0, -1, 132},
    {"blue_car", 1, -1, 133},
    {"blue_car", 2, -1, 134},
    {"blue_car", 3, -1, 135},
    {"blue_truck", 0, -1, 136},
    {"blue_truck", 1, -1, 137},
    {"blue_truck", 2, -1, 138},
    {"blue_truck", 3, -1, 139},
    {"boulder_0", 0, -1, 140},
    {"boulder_0", 1, -1, 141},
    {"boulder_0", 2, -1, 142},
    {"boulder_0", 3, -1, 143},
    {"boulder_1", 0, -1, 144},
    {"boulder_1", 1, -1, 145},
    {"boulder_1", 2, -1, 146},
    {"boulder_1", 3, -1, 147},
    {"chicken", 0, 0, 148},
    {"chicken", 0, 1, 149},
    {"chicken", 0, 2, 150},
    {"chicken", 0, 3, 151},
    {"chicken", 0, 4, 152},
    {"chicken", 0, 5, 153},
    {"chicken", 0, 6, 154},
    {"chicken", 0, 7, 155},
    {"chicken", 0, 8, 156},
    {"chicken", 0, 9, 157},
    {"chicken", 0, 10, 158},
    {"chicken", 1, 0, 159},
    {"chicken", 1, 1, 160},
    {"chicken", 1, 2, 161},
    {"chicken", 1, 3, 162},
    {"chicken", 1, 4, 163},
    {"chicken", 1, 5, 164},
    {"chicken", 1, 6, 165},
    {"chicken", 1, 7, 166},
    {"chicken", 1, 8, 167},
    {"chicken", 1, 9, 168},
    {"chicken", 1, 10, 169},
    {"chicken", 2, 0, 170},
    {"chicken", 2, 1, 171},
    {"chicken", 2, 2, 172},
    {"chicken", 2, 3, 173},
    {"chicken", 2, 4, 174},
    {"chicken", 2, 5, 175},
    {"chicken", 2, 6, 176},
    {"chicken", 2, 7, 177},
    {"chicken", 2, 8, 178},
    {"chicken", 2, 9, 179},
    {"chicken", 2, 10, 180},
    {"chicken", 3, 0, 181},
    {"chicken", 3, 1, 182},
    {"chicken", 3, 2, 183},
    {"chicken", 3, 3, 184},
    {"chicken", 3, 4, 185},
    {"chicken", 3, 5, 186},
    {"chicken", 3, 6, 187},
    {"chicken", 3, 7, 188},
    {"chicken", 3, 8, 189},
    {"chicken", 3, 9, 190},
    {"chicken", 3, 10, 191},
    {"chicken", 4, 0, 192},
    {"chicken", 4, 1, 193},
    {"chicken", 4, 2, 194},
    {"chicken", 4, 3, 195},
    {"chicken", 4, 4, 196},
    {"chicken", 4, 5, 197},
    {"chicken", 4, 6, 198},
    {"chicken", 4, 7, 199},
    {"chicken", 4, 8, 200},
    {"chicken", 4, 9, 201},
    {"chicken", 4, 10, 202},
    {"chicken", 5, 0, 203},
    {"chicken", 5, 1, 204},
    {"chicken", 5, 2, 205},
    {"chicken", 5, 3, 206},
    {"chicken", 5, 4, 207},
    {"chicken", 5, 5, 208},
    {"chicken", 5, 6, 209},
    {"chicken", 5, 7, 210},
    {"chicken", 5, 8, 211},
    {"chicken", 5, 9, 212},
    {"chicken", 5, 10, 213},
    {"chicken", 6, 0, 214},
    {"chicken", 6, 1, 215},
    {"chicken", 6, 2, 216},
    {"chicken", 6, 3, 217},
    {"chicken", 6, 4, 218},
    {"chicken", 6, 5, 219},
    {"chicken", 6, 6, 220},
    {"chicken", 6, 7, 221},
    {"chicken", 6, 8, 222},
    {"chicken", 6, 9, 223},
    {"chicken", 6, 10, 224},
    {"chicken", 7, 0, 225},
    {"chicken", 7, 1, 226},
    {"chicken", 7, 2, 227},
    {"chicken", 7, 3, 228},
    {"chicken", 7, 4, 229},
    {"chicken", 7, 5, 230},
    {"chicken", 7, 6, 231},
    {"chicken", 7, 7, 232},
    {"chicken", 7, 8, 233},
    {"chicken", 7, 9, 234},
    {"chicken", 7, 10, 235},
    {"chicken", 8, 0, 236},
    {"chicken", 8, 1, 237},
    {"chicken", 8, 2, 238},
    {"chicken", 8, 3, 239},
    {"chicken", 8, 4, 240},
    {"chicken", 8, 5, 241},
    {"chicken", 8, 6, 242},
    {"chicken", 8, 7, 243},
    {"chicken", 8, 8, 244},
    {"chicken", 8, 9, 245},
    {"chicken", 8, 10, 246},
    {"chicken", 9, 0, 247},
    {"chicken", 9, 1, 248},
    {"chicken", 9, 2, 249},
    {"chicken", 9, 3, 250},
    {"chicken", 9, 4, 251},
    {"chicken", 9, 5, 252},
    {"chicken", 9, 6, 253},
    {"chicken", 9, 7, 254},
    {"chicken", 9, 8, 255},
    {"chicken", 9, 9, 256},
    {"chicken", 9, 10, 257},
    {"chicken", 10, 0, 258},
    {"chicken", 10, 1, 259},
    {"chicken", 10, 2, 260},
    {"chicken", 10, 3, 261},
    {"chicken", 10, 4, 262},
    {"chicken", 10, 5, 263},
    {"chicken", 10, 6, 264},
    {"chicken", 10, 7, 265},
    {"chicken", 10, 8, 266},
    {"chicken", 10, 9, 267},
    {"chicken", 10, 10, 268},
    {"chicken", 11, 0, 269},
    {"chicken", 11, 1, 270},
    {"chicken", 11, 2, 271},
    {"chicken", 11, 3, 272},
    {"chicken", 11, 4, 273},
    {"chicken", 11, 5, 274},
    {"chicken", 11, 6, 275},
    {"chicken", 11, 7, 276},
    {"chicken", 11, 8, 277},
    {"chicken", 11, 9, 278},
    {"chicken", 11, 10, 279},
    {"grass_0", 0, -1, 280},
    {"grass_1", 0, -1, 281},
    {"green_car", 0, -1, 282},
    {"green_car", 1, -1, 283},
    {"green_car", 2, -1, 284},
    {"green_car", 3, -1, 285},
    {"lily_pad", 0, -1, 286},
    {"lily_pad", 1, -1, 287},
    {"lily_pad", 2, -1, 288},
    {"lily_pad", 3, -1, 289},
    {"log_0", 0, -1, 290},
    {"log_0", 1, -1, 291},
    {"log_0", 2, -1, 292},
    {"log_0", 3, -1, 293},
    {"log_1", 0, -1, 294},
    {"log_1", 1, -1, 295},
    {"log_1", 2, -1, 296},
    {"log_1", 3, -1, 297},
    {"log_2", 0, -1, 298},
    {"log_2", 1, -1, 299},
    {"log_2", 2, -1, 300},
    {"log_2", 3, -1, 301},
    {"log_3", 0, -1, 302},
    {"log_3", 1, -1, 303},
    {"log_3", 2, -1, 304},
    {"log_3", 3, -1, 305},
    {"orange_car", 0, -1, 306},
    {"orange_car", 1, -1, 307},
    {"orange_car", 2, -1, 308},
    {"orange_car", 3, -1, 309},
    {"police_car", 0, -1, 310},
    {"police_car", 1, -1, 311},
    {"police_car", 2, -1, 312},
    {"police_car", 3, -1, 313},
    {"purple_car", 0, -1, 314},
    {"purple_car", 1, -1, 315},
    {"purple_car", 2, -1, 316},
    {"purple_car", 3, -1, 317},
    {"railroad", 0, -1, 318},
    {"red_truck", 0, -1, 319},
    {"red_truck", 1, -1, 320},
    {"red_truck", 2, -1, 321},
    {"red_truck", 3, -1, 322},
    {"river", 0, -1, 323},
    {"road_0", 0, -1, 324},
    {"road_1", 0, -1, 325},
    {"taxi", 0, -1, 326},
    {"taxi", 1, -1, 327},
    {"taxi", 2, -1, 328},
    {"taxi", 3, -1, 329},
    {"train_back", 0, -1, 330},
    {"train_back", 1, -1, 331},
    {"train_back", 2, -1, 332},
    {"train_back", 3, -1, 333},
    {"train_front", 0, -1, 334},
    {"train_front", 1, -1, 335},
    {"train_front", 2, -1, 336},
    {"train_front", 3, -1, 337},
    {"train_light_active_0", 0, -1, 338},
    {"train_light_active_0", 1, -1, 339},
    {"train_light_active_0", 2, -1, 340},
    {"train_light_active_0", 3, -1, 341},
    {"train_light_active_1", 0, -1, 342},
    {"train_light_active_1", 1, -1, 343},
    {"train_light_active_1", 2, -1, 344},
    {"train_light_active_1", 3, -1, 345},
    {"train_light_inactive", 0, -1, 346},
    {"train_light_inactive", 1, -1, 347},
    {"train_light_inactive", 2, -1, 348},
    {"train_light_inactive", 3, -1, 349},
    {"train_middle", 0, -1, 350},
    {"train_middle", 1, -1, 351},
    {"train_middle", 2, -1, 352},
    {"train_middle", 3, -1, 353},
    {"tree_0", 0, -1, 354},
    {"tree_0", 1, -1, 355},
    {"tree_0", 2, -1, 356},
    {"tree_0", 3, -1, 357},
    {"tree_1", 0, -1, 358},
    {"tree_1", 1, -1, 359},
    {"tree_1", 2, -1, 360},
    {"tree_1", 3, -1, 361},
    {"tree_2", 0, -1, 362},
    {"tree_2", 1, -1, 363},
    {"tree_2", 2, -1, 364},
    {"tree_2", 3, -1, 365},
    {"tree_3", 0, -1, 366},
    {"tree_3", 1, -1, 367},
    {"tree_3", 2, -1, 368},
    {"tree_3", 3, -1, 369},
    {"logo", 0, -1, 370},
};
#define BH_SPRITE_NAME_COUNT 371
#define BH_HERO_PHASE_COUNT 11
#define BH_ROT_MAX 12

#endif
