// Generated by tools/pack_amiga_sprites.py - do not edit.
// Fixed palette slots for the menus, so the Amiga shows the SAME colours as the console ports
// (src/ui/screens.cpp) instead of picking the lightest colour it can find in the art.
#ifndef BH_UI_COLOURS_H
#define BH_UI_COLOURS_H

#define BH_UI_BAR_A      2   /* 0x6A40EB */
#define BH_UI_BAR_B      3   /* 0x6A8FEB */
#define BH_UI_SELECTED   4   /* 0xF8E84D */
#define BH_UI_TEXT       5   /* 0xFFFFFF */
#define BH_UI_OUTLINE    6   /* 0x000000 */
#define BH_UI_GO_A       7   /* 0x3640EB */
#define BH_UI_GO_B       8   /* 0x368FEB */
#define BH_UI_GO_C       9   /* 0x36D6EB */

// The SYSTEM's own registers, never written by the art. The Intuition bar draws in the pens
// below, and the mouse pointer is hardware sprite 0, which reads registers 17, 18 and 19 -
// so those three must hold pointer colours, not whatever the sprites happened to need.
#define BH_SYS_BAR_TEXT    10  /* 0xFFFFFF */
#define BH_SYS_BAR_FILL    11  /* 0x205A8C */
#define BH_SYS_BAR_EDGE    12  /* 0x000000 */
#define BH_SYS_SPARE_13    13  /* 0x69C9E6 */
#define BH_SYS_SPARE_14    14  /* 0x909090 */
#define BH_SYS_SPARE_15    15  /* 0xB0B0B0 */
#define BH_SYS_SPARE_16    16  /* 0xD0D0D0 */
#define BH_SYS_POINTER_1   17  /* 0xFFFFFF */
#define BH_SYS_POINTER_2   18  /* 0x000000 */
#define BH_SYS_POINTER_3   19  /* 0xFF8A00 */

#endif
